---
- name: Install Ruby && Bundler
  hosts: all
  become: true
  tasks:
  # Установим в цикле все зависимости
  - name: Install ruby and rubygems and required packages
    update_cache: yes
    apt: "name={{ item }} state=present"
    loop:
      - ruby-full
      - ruby-bundler
      - build-essential
