version: '3.3'
services:
  post_db:
    env_file: .env
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db

  ui:
    env_file: .env
    image: ${USER_NAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${APP_PORT}:${APP_PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USER_NAME}/post
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    env_file: .env
    image: ${USER_NAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:

